const translations = {
  en: {
    "nav.features": "Features",
    "nav.support": "Support",
    "nav.privacy": "Privacy",
    "hero.eyebrow": "iPhone & iPad game",
    "hero.title": "Apex Ryde",
    "hero.text": "A first-person supersport motorcycle game. Real friction-circle physics, a proper sequential gearbox, and an endless golden-hour coastal road that never rides the same way twice.",
    "hero.cta": "Coming to the App Store",
    "hero.support": "Get support",
    "features.eyebrow": "Built on real riding",
    "features.title": "Every system modeled on how a bike actually behaves.",
    "features.physics.title": "Friction-circle physics",
    "features.physics.text": "Braking, throttle, and lean all draw from one shared grip budget. Push past it while leaned over and you lowside — exactly like the real thing.",
    "features.gearbox.title": "A real sequential gearbox",
    "features.gearbox.text": "Shift 1 N 2 3 4 5 6 with a half or full swipe, just like a lever. Quickshifter cuts ignition for 80 ms on upshifts — no clutch, no compromise.",
    "features.steering.title": "Tilt steering",
    "features.steering.text": "Lean your phone to lean the bike, with trail-inspired self-centering when you're upright. A touch-drag fallback covers the Simulator and accessibility needs.",
    "features.roads.title": "Endless coastal roads",
    "features.roads.text": "Every run generates a new twisty, golden-hour coastal road — sweepers, hairpins, chicanes, crests. Same seed, same run, every time: fully deterministic.",
    "features.gamecenter.title": "Game Center built in",
    "features.gamecenter.text": "Chase the longest-ride leaderboard and unlock achievements for your first wheelie, your first 10 km, and fifty near-misses.",
    "features.universal.title": "iPhone and iPad",
    "features.universal.text": "One universal app for iPhone and iPad, landscape-only, tuned for both touch and tilt.",
    "gallery.eyebrow": "In the cockpit",
    "gallery.title": "See it in action.",
    "gallery.menu.caption": "Main menu — shift into first and go.",
    "gallery.riding.caption": "TFT dash, clip-ons, and the road ahead.",
    "gallery.tutorial.caption": "Learn the shifter before you ride for real.",
    "skill.eyebrow": "The skill ceiling",
    "skill.title": "Any of these ends the run.",
    "skill.text": "There's no health bar and no second chance. Ride within the friction circle, or don't ride at all.",
    "skill.lowside": "Lowside",
    "skill.highside": "Highside",
    "skill.loopout": "Wheelie loop-out",
    "skill.wide": "Running wide",
    "skill.obstacle": "Obstacle hit",
    "download.title": "Coming to the App Store.",
    "download.text": "Apex Ryde is in final testing for iPhone and iPad. Get support or check back soon.",
    "download.button": "Coming soon",
    "footer.support": "Support",
    "footer.privacy": "Privacy",
    "footer.marketing": "Marketing page",
    "support.eyebrow": "Support",
    "support.title": "Apex Ryde Support",
    "support.intro": "Questions about riding, controls, Game Center, or something that doesn't feel right? Start here.",
    "support.contact.title": "Contact",
    "support.contact.text": "For support, include your device model, iOS version, and a short description of the issue.",
    "support.contact.button": "Email support",
    "support.contact.note": "Current support email: pcesnek290@gmail.com",
    "support.gamecenter.title": "Game Center",
    "support.gamecenter.text": "Leaderboards and achievements use Apple's Game Center. If scores aren't syncing, check that you're signed in to Game Center under iOS Settings.",
    "support.data.title": "Run history and settings",
    "support.data.text": "Your run history, personal bests, and settings are stored on your device.",
    "support.offline.title": "Playing offline",
    "support.offline.text": "Apex Ryde is fully playable offline. Game Center features need a connection to sync; scores are saved locally either way.",
    "faq.title": "FAQ",
    "faq.languages.summary": "Which languages are supported?",
    "faq.languages.text": "Apex Ryde is localized in English, Slovak, and Czech.",
    "faq.tilt.summary": "What if tilt steering doesn't work?",
    "faq.tilt.text": "In the Simulator, or if motion access is unavailable, Apex Ryde automatically falls back to touch-drag steering.",
    "faq.gamecenter.summary": "Do I have to use Game Center?",
    "faq.gamecenter.text": "No. If Game Center is unavailable or declined, Apex Ryde keeps your scores locally with no nagging.",
    "faq.offline.summary": "Does it need an internet connection?",
    "faq.offline.text": "No. Apex Ryde is fully playable offline.",
    "privacy.eyebrow": "Privacy",
    "privacy.title": "Privacy Policy",
    "privacy.updated": "Last updated: July 5, 2026",
    "privacy.overview.title": "Overview",
    "privacy.overview.text": "Apex Ryde is built to keep your data on your device. There is no account system, no advertising network, and no analytics service in the app.",
    "privacy.storage.summary": "Information the app stores",
    "privacy.storage.text": "Apex Ryde stores your settings, run history, and personal bests locally on your device so the app can work.",
    "privacy.gamecenter.summary": "Game Center",
    "privacy.gamecenter.text": "If you sign in to Game Center, your Game Center identity and scores are shared with Apple's Game Center service to power leaderboards and achievements. That data is governed by Apple's own privacy policy.",
    "privacy.motion.summary": "Motion data",
    "privacy.motion.text": "Tilt steering reads your device's motion data in real time to control the bike. This data is processed on-device only and is never recorded or transmitted anywhere.",
    "privacy.third.summary": "Third parties",
    "privacy.third.text": "Apex Ryde uses Apple services such as Game Center and the App Store. Those services are governed by Apple's privacy policies. We do not sell your personal information.",
    "privacy.support.summary": "Support email",
    "privacy.support.text": "If you contact support by email, we receive the information you choose to send, such as your email address, device details, and message. We use it only to respond to your request.",
    "privacy.delete.summary": "Deleting your data",
    "privacy.delete.text": "All app data is stored locally. You can remove it by deleting the app from your device.",
    "privacy.contact.summary": "Contact",
    "privacy.contact.text": "For privacy questions, email pcesnek290@gmail.com.",
    "meta.home.title": "Apex Ryde | First-Person Motorcycle Game for iPhone & iPad",
    "meta.home.description": "Apex Ryde is a first-person supersport motorcycle game for iPhone and iPad with real friction-circle physics, a sequential gearbox, tilt steering, and endless procedural coastal roads.",
    "meta.support.title": "Apex Ryde Support | Help, Game Center, and Controls",
    "meta.support.description": "Get support for Apex Ryde on iPhone and iPad, including Game Center, controls, run history, and offline play.",
    "meta.privacy.title": "Apex Ryde Privacy Policy",
    "meta.privacy.description": "Read the Apex Ryde privacy policy covering local run history, Game Center data sharing, on-device motion processing, and support email data."
  },
  sk: {
    "nav.features": "Funkcie",
    "nav.support": "Podpora",
    "nav.privacy": "Súkromie",
    "hero.eyebrow": "Hra pre iPhone a iPad",
    "hero.title": "Apex Ryde",
    "hero.text": "Pretekárska hra na motorke z pohľadu jazdca. Skutočná fyzika trakčného kruhu, poriadna sekvenčná prevodovka a nekonečná pobrežná cesta v zlatej hodinke, ktorá sa nikdy neopakuje rovnako.",
    "hero.cta": "Čoskoro v App Store",
    "hero.support": "Získať podporu",
    "features.eyebrow": "Postavené na skutočnom jazdení",
    "features.title": "Každý systém modelovaný podľa toho, ako sa motorka naozaj správa.",
    "features.physics.title": "Fyzika trakčného kruhu",
    "features.physics.text": "Brzdenie, plyn aj náklon čerpajú z jedného spoločného rozpočtu trakcie. Prekroč ho v náklone a padneš na vnútornú stranu — presne ako v realite.",
    "features.gearbox.title": "Skutočná sekvenčná prevodovka",
    "features.gearbox.text": "Radíš 1 N 2 3 4 5 6 polovičným alebo plným ťahom, presne ako pákou. Quickshifter pri podradení preruší zapaľovanie na 80 ms — bez spojky, bez kompromisov.",
    "features.steering.title": "Riadenie náklonom telefónu",
    "features.steering.text": "Nakloň telefón a motorka sa nakloní s tebou, so samovyrovnávaním inšpirovaným geometriou riadenia, keď si vzpriamený. Náhradné ovládanie ťahom prsta funguje v simulátore aj pri obmedzeniach prístupnosti.",
    "features.roads.title": "Nekonečné pobrežné cesty",
    "features.roads.text": "Každá jazda vygeneruje novú kľukatú pobrežnú cestu v zlatej hodinke — zákruty, vlásenky, esíčka, kopce. Rovnaký seed, rovnaká jazda, vždy identicky: plne deterministické.",
    "features.gamecenter.title": "Game Center v aplikácii",
    "features.gamecenter.text": "Naháňaj rebríček najdlhšej jazdy a odomkni achievementy za prvý wheelie, prvých 10 km a päťdesiat tesných priblížení.",
    "features.universal.title": "iPhone aj iPad",
    "features.universal.text": "Jedna univerzálna aplikácia pre iPhone aj iPad, iba na šírku, doladená pre dotyk aj náklon.",
    "gallery.eyebrow": "V kokpite",
    "gallery.title": "Pozri si to v akcii.",
    "gallery.menu.caption": "Hlavné menu — zaraď jednotku a choď.",
    "gallery.riding.caption": "TFT palubovka, plocháče a cesta pred tebou.",
    "gallery.tutorial.caption": "Nauč sa radenie skôr, než vyrazíš naostro.",
    "skill.eyebrow": "Strop zručnosti",
    "skill.title": "Ktorákoľvek z týchto vecí ukončí jazdu.",
    "skill.text": "Nie je tu žiadny ukazovateľ zdravia ani druhá šanca. Jazdi v rámci trakčného kruhu, alebo nejazdi vôbec.",
    "skill.lowside": "Pád na vnútornú stranu",
    "skill.highside": "Highside",
    "skill.loopout": "Prevrátenie pri wheelie",
    "skill.wide": "Vyjazdenie zo zákruty",
    "skill.obstacle": "Náraz do prekážky",
    "download.title": "Čoskoro v App Store.",
    "download.text": "Apex Ryde je vo finálnom testovaní pre iPhone a iPad. Získaj podporu alebo sa vráť neskôr.",
    "download.button": "Čoskoro",
    "footer.support": "Podpora",
    "footer.privacy": "Súkromie",
    "footer.marketing": "Marketingová stránka",
    "support.eyebrow": "Podpora",
    "support.title": "Podpora Apex Ryde",
    "support.intro": "Otázky ohľadom jazdenia, ovládania, Game Center alebo niečoho, čo nefunguje správne? Začni tu.",
    "support.contact.title": "Kontakt",
    "support.contact.text": "Pre podporu uveď model zariadenia, verziu iOS a krátky popis problému.",
    "support.contact.button": "Napísať podpore",
    "support.contact.note": "Aktuálny e-mail podpory: pcesnek290@gmail.com",
    "support.gamecenter.title": "Game Center",
    "support.gamecenter.text": "Rebríčky a achievementy používajú Apple Game Center. Ak sa skóre nesynchronizuje, over, či si prihlásený do Game Center v nastaveniach iOS.",
    "support.data.title": "História jázd a nastavenia",
    "support.data.text": "Tvoja história jázd, osobné rekordy a nastavenia sú uložené v zariadení.",
    "support.offline.title": "Hranie offline",
    "support.offline.text": "Apex Ryde je plne hrateľné offline. Funkcie Game Center potrebujú pripojenie na synchronizáciu, no skóre sa ukladá lokálne v oboch prípadoch.",
    "faq.title": "Časté otázky",
    "faq.languages.summary": "Aké jazyky aplikácia podporuje?",
    "faq.languages.text": "Apex Ryde je lokalizovaný do angličtiny, slovenčiny a češtiny.",
    "faq.tilt.summary": "Čo ak riadenie náklonom nefunguje?",
    "faq.tilt.text": "V simulátore, alebo ak nie je dostupný prístup k pohybu zariadenia, Apex Ryde automaticky prepne na ovládanie ťahom prsta.",
    "faq.gamecenter.summary": "Musím používať Game Center?",
    "faq.gamecenter.text": "Nie. Ak je Game Center nedostupný alebo ho odmietneš, Apex Ryde si skóre naďalej ukladá lokálne bez otravovania.",
    "faq.offline.summary": "Potrebuje internetové pripojenie?",
    "faq.offline.text": "Nie. Apex Ryde je plne hrateľné offline.",
    "privacy.eyebrow": "Súkromie",
    "privacy.title": "Zásady ochrany súkromia",
    "privacy.updated": "Naposledy aktualizované: 5. júla 2026",
    "privacy.overview.title": "Prehľad",
    "privacy.overview.text": "Apex Ryde je navrhnutý tak, aby tvoje dáta zostali v zariadení. V aplikácii neprevádzkujeme vlastný systém účtov, reklamnú sieť ani analytickú službu.",
    "privacy.storage.summary": "Informácie uložené aplikáciou",
    "privacy.storage.text": "Apex Ryde lokálne v zariadení ukladá tvoje nastavenia, históriu jázd a osobné rekordy, aby aplikácia mohla fungovať.",
    "privacy.gamecenter.summary": "Game Center",
    "privacy.gamecenter.text": "Ak sa prihlásiš do Game Center, tvoja identita a skóre v Game Center sa zdieľajú so službou Apple Game Center kvôli rebríčkom a achievementom. Tieto dáta sa riadia vlastnými zásadami ochrany súkromia spoločnosti Apple.",
    "privacy.motion.summary": "Pohybové dáta",
    "privacy.motion.text": "Riadenie náklonom číta pohybové dáta zariadenia v reálnom čase, aby ovládalo motorku. Tieto dáta sa spracúvajú iba lokálne v zariadení a nikdy sa nezaznamenávajú ani neprenášajú.",
    "privacy.third.summary": "Tretie strany",
    "privacy.third.text": "Apex Ryde používa služby Apple, napríklad Game Center a App Store. Tieto služby sa riadia zásadami ochrany súkromia spoločnosti Apple. Tvoje osobné informácie nepredávame.",
    "privacy.support.summary": "E-mail podpory",
    "privacy.support.text": "Ak kontaktuješ podporu e-mailom, dostaneme informácie, ktoré sa rozhodneš poslať, napríklad e-mailovú adresu, údaje o zariadení a správu. Použijeme ich iba na odpoveď na tvoju požiadavku.",
    "privacy.delete.summary": "Vymazanie dát",
    "privacy.delete.text": "Všetky dáta aplikácie sú uložené lokálne. Môžeš ich odstrániť vymazaním aplikácie zo zariadenia.",
    "privacy.contact.summary": "Kontakt",
    "privacy.contact.text": "S otázkami k súkromiu napíš na pcesnek290@gmail.com.",
    "meta.home.title": "Apex Ryde | Motorkárska hra z pohľadu jazdca pre iPhone a iPad",
    "meta.home.description": "Apex Ryde je motorkárska hra z pohľadu jazdca pre iPhone a iPad so skutočnou fyzikou trakčného kruhu, sekvenčnou prevodovkou, riadením náklonom a nekonečnými procedurálnymi pobrežnými cestami.",
    "meta.support.title": "Podpora Apex Ryde | Pomoc, Game Center a ovládanie",
    "meta.support.description": "Získaj podporu pre Apex Ryde na iPhone a iPad vrátane Game Center, ovládania, histórie jázd a offline hrania.",
    "meta.privacy.title": "Zásady ochrany súkromia Apex Ryde",
    "meta.privacy.description": "Prečítaj si zásady ochrany súkromia Apex Ryde o lokálnej histórii jázd, zdieľaní dát cez Game Center, lokálnom spracovaní pohybu a dátach z e-mailu podpory."
  },
  cs: {
    "nav.features": "Funkce",
    "nav.support": "Podpora",
    "nav.privacy": "Soukromí",
    "hero.eyebrow": "Hra pro iPhone a iPad",
    "hero.title": "Apex Ryde",
    "hero.text": "Motorkářská hra z pohledu jezdce. Skutečná fyzika třecí kružnice, pořádná sekvenční převodovka a nekonečná pobřežní silnice ve zlaté hodince, která se nikdy neopakuje stejně.",
    "hero.cta": "Již brzy v App Store",
    "hero.support": "Získat podporu",
    "features.eyebrow": "Postaveno na skutečném jezdění",
    "features.title": "Každý systém modelovaný podle toho, jak se motorka opravdu chová.",
    "features.physics.title": "Fyzika třecí kružnice",
    "features.physics.text": "Brzdění, plyn i náklon čerpají ze společného rozpočtu trakce. Překroč ho v náklonu a padneš na vnitřní stranu — přesně jako v realitě.",
    "features.gearbox.title": "Skutečná sekvenční převodovka",
    "features.gearbox.text": "Řaď 1 N 2 3 4 5 6 polovičním nebo plným tahem, přesně jako pákou. Quickshifter při podřazení přeruší zapalování na 80 ms — bez spojky, bez kompromisů.",
    "features.steering.title": "Řízení náklonem telefonu",
    "features.steering.text": "Nakloň telefon a motorka se nakloní s tebou, se samovyrovnáváním inspirovaným geometrií řízení, když jsi vzpřímený. Náhradní ovládání tahem prstu funguje v simulátoru i při omezeních přístupnosti.",
    "features.roads.title": "Nekonečné pobřežní silnice",
    "features.roads.text": "Každá jízda vygeneruje novou klikatou pobřežní silnici ve zlaté hodince — zatáčky, vlásenky, esíčka, kopce. Stejný seed, stejná jízda, vždy identicky: plně deterministické.",
    "features.gamecenter.title": "Game Center v aplikaci",
    "features.gamecenter.text": "Honíme se za žebříčkem nejdelší jízdy a odemkni achievementy za první wheelie, prvních 10 km a padesát těsných přiblížení.",
    "features.universal.title": "iPhone i iPad",
    "features.universal.text": "Jedna univerzální aplikace pro iPhone i iPad, pouze na šířku, doladěná pro dotyk i náklon.",
    "gallery.eyebrow": "V kokpitu",
    "gallery.title": "Podívej se na to v akci.",
    "gallery.menu.caption": "Hlavní menu — zařaď jedničku a jeď.",
    "gallery.riding.caption": "TFT paluba, plocháče a cesta před tebou.",
    "gallery.tutorial.caption": "Nauč se řazení, než vyrazíš naostro.",
    "skill.eyebrow": "Strop dovednosti",
    "skill.title": "Kterákoli z těchto věcí ukončí jízdu.",
    "skill.text": "Není tu žádný ukazatel zdraví ani druhá šance. Jezdi v rámci třecí kružnice, nebo nejezdi vůbec.",
    "skill.lowside": "Pád na vnitřní stranu",
    "skill.highside": "Highside",
    "skill.loopout": "Převrácení při wheelie",
    "skill.wide": "Vyjetí ze zatáčky",
    "skill.obstacle": "Náraz do překážky",
    "download.title": "Již brzy v App Store.",
    "download.text": "Apex Ryde je ve finálním testování pro iPhone a iPad. Získej podporu nebo se vrať později.",
    "download.button": "Již brzy",
    "footer.support": "Podpora",
    "footer.privacy": "Soukromí",
    "footer.marketing": "Marketingová stránka",
    "support.eyebrow": "Podpora",
    "support.title": "Podpora Apex Ryde",
    "support.intro": "Otázky ohledně jízdy, ovládání, Game Center nebo něčeho, co nefunguje správně? Začni tady.",
    "support.contact.title": "Kontakt",
    "support.contact.text": "Pro podporu uveď model zařízení, verzi iOS a krátký popis problému.",
    "support.contact.button": "Napsat podpoře",
    "support.contact.note": "Aktuální e-mail podpory: pcesnek290@gmail.com",
    "support.gamecenter.title": "Game Center",
    "support.gamecenter.text": "Žebříčky a achievementy používají Apple Game Center. Pokud se skóre nesynchronizuje, ověř, že jsi přihlášen do Game Center v nastavení iOS.",
    "support.data.title": "historie jízd a nastavení",
    "support.data.text": "Tvoje historie jízd, osobní rekordy a nastavení jsou uložené v zařízení.",
    "support.offline.title": "Hraní offline",
    "support.offline.text": "Apex Ryde je plně hratelné offline. Funkce Game Center potřebují připojení k synchronizaci, ale skóre se ukládá lokálně v obou případech.",
    "faq.title": "Časté dotazy",
    "faq.languages.summary": "Jaké jazyky aplikace podporuje?",
    "faq.languages.text": "Apex Ryde je lokalizovaný do angličtiny, slovenštiny a češtiny.",
    "faq.tilt.summary": "Co když řízení náklonem nefunguje?",
    "faq.tilt.text": "V simulátoru, nebo pokud není dostupný přístup k pohybu zařízení, Apex Ryde automaticky přepne na ovládání tahem prstu.",
    "faq.gamecenter.summary": "Musím používat Game Center?",
    "faq.gamecenter.text": "Ne. Pokud je Game Center nedostupný nebo ho odmítneš, Apex Ryde si skóre nadále ukládá lokálně bez obtěžování.",
    "faq.offline.summary": "Potřebuje internetové připojení?",
    "faq.offline.text": "Ne. Apex Ryde je plně hratelné offline.",
    "privacy.eyebrow": "Soukromí",
    "privacy.title": "Zásady ochrany soukromí",
    "privacy.updated": "Naposledy aktualizováno: 5. července 2026",
    "privacy.overview.title": "Přehled",
    "privacy.overview.text": "Apex Ryde je navržený tak, aby tvoje data zůstala v zařízení. V aplikaci neprovozujeme vlastní systém účtů, reklamní síť ani analytickou službu.",
    "privacy.storage.summary": "Informace uložené aplikací",
    "privacy.storage.text": "Apex Ryde lokálně v zařízení ukládá tvoje nastavení, historii jízd a osobní rekordy, aby aplikace mohla fungovat.",
    "privacy.gamecenter.summary": "Game Center",
    "privacy.gamecenter.text": "Pokud se přihlásíš do Game Center, tvoje identita a skóre v Game Center se sdílí se službou Apple Game Center kvůli žebříčkům a achievementům. Tato data se řídí vlastními zásadami ochrany soukromí společnosti Apple.",
    "privacy.motion.summary": "Pohybová data",
    "privacy.motion.text": "Řízení náklonem čte pohybová data zařízení v reálném čase, aby ovládalo motorku. Tato data se zpracovávají pouze lokálně v zařízení a nikdy se nezaznamenávají ani nepřenášejí.",
    "privacy.third.summary": "Třetí strany",
    "privacy.third.text": "Apex Ryde používá služby Apple, například Game Center a App Store. Tyto služby se řídí zásadami ochrany soukromí společnosti Apple. Tvoje osobní informace neprodáváme.",
    "privacy.support.summary": "E-mail podpory",
    "privacy.support.text": "Pokud kontaktuješ podporu e-mailem, obdržíme informace, které se rozhodneš poslat, například e-mailovou adresu, údaje o zařízení a zprávu. Použijeme je pouze k odpovědi na tvůj požadavek.",
    "privacy.delete.summary": "Smazání dat",
    "privacy.delete.text": "Všechna data aplikace jsou uložená lokálně. Můžeš je odstranit smazáním aplikace ze zařízení.",
    "privacy.contact.summary": "Kontakt",
    "privacy.contact.text": "S dotazy k soukromí napiš na pcesnek290@gmail.com.",
    "meta.home.title": "Apex Ryde | Motorkářská hra z pohledu jezdce pro iPhone a iPad",
    "meta.home.description": "Apex Ryde je motorkářská hra z pohledu jezdce pro iPhone a iPad se skutečnou fyzikou třecí kružnice, sekvenční převodovkou, řízením náklonem a nekonečnými procedurálními pobřežními silnicemi.",
    "meta.support.title": "Podpora Apex Ryde | Pomoc, Game Center a ovládání",
    "meta.support.description": "Získej podporu pro Apex Ryde na iPhone a iPad včetně Game Center, ovládání, historie jízd a offline hraní.",
    "meta.privacy.title": "Zásady ochrany soukromí Apex Ryde",
    "meta.privacy.description": "Přečti si zásady ochrany soukromí Apex Ryde o lokální historii jízd, sdílení dat přes Game Center, lokálním zpracování pohybu a datech z e-mailu podpory."
  }
};

const supportedLanguages = Object.keys(translations);
const browserLanguage = navigator.language.slice(0, 2);
const savedLanguage = localStorage.getItem("apex-ryde-language");
const initialLanguage = supportedLanguages.includes(savedLanguage)
  ? savedLanguage
  : supportedLanguages.includes(browserLanguage)
    ? browserLanguage
    : "en";

const pageMetaKey = document.body.dataset.page || "home";

function setLanguage(language) {
  const dictionary = translations[language] || translations.en;
  document.documentElement.lang = language;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) {
      element.textContent = dictionary[key];
    }
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === language);
    button.setAttribute("aria-pressed", String(button.dataset.lang === language));
  });

  const titleKey = `meta.${pageMetaKey}.title`;
  const descriptionKey = `meta.${pageMetaKey}.description`;
  if (dictionary[titleKey]) {
    document.title = dictionary[titleKey];
  }
  const descriptionTag = document.querySelector('meta[name="description"]');
  if (descriptionTag && dictionary[descriptionKey]) {
    descriptionTag.setAttribute("content", dictionary[descriptionKey]);
  }

  localStorage.setItem("apex-ryde-language", language);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

setLanguage(initialLanguage);
